DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'kurrier') THEN
CREATE ROLE kurrier LOGIN PASSWORD 'replace_with_your_password';
END IF;
END
$$;
CREATE SCHEMA IF NOT EXISTS auth;

ALTER SCHEMA public OWNER TO kurrier;
ALTER SCHEMA auth OWNER TO kurrier;
GRANT ALL ON SCHEMA public TO kurrier;
GRANT ALL ON SCHEMA auth TO kurrier;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kurrier;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO kurrier;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kurrier;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO kurrier;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO kurrier;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO kurrier;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth
GRANT ALL ON TABLES TO kurrier;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth
GRANT ALL ON SEQUENCES TO kurrier;
